export const NOTIFY_USER = "NOTIFY_USER";
export const UPDATE_BALANCE = "UPDATE_BALANCE";
export const GET_ALL_CLIENTS = "GET_ALL_CLIENTS";
export const GET_CLIENT = "GET_CLIENT";
export const UPDATE_CLIENT_INFO = "UPDATE_CLIENT_INFO";
export const DELETE_CLIENT = "DELETE_CLIENT";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const SIGNED_OUT_SUCCESS = "SIGNED_OUT_SUCCESS";
export const ERROR_MESSAGE = "ERROR_MESSAGE";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";

export const DISABLE_BALANCE_ON_ADD = "DISABLE_BALANCE_ON_ADD";
export const DISABLE_BALANCE_ON_EDIT = "DISABLE_BALANCE_ON_EDIT";
export const ALLOW_REGISTRATION = "ALLOW_REGISTRATION";
export const SEARCH_CLIENT = "SEARCH_CLIENT";
